#!/bin/bash

this_dir="$(dirname $0)"

export ANSIBLE_NOCOWS=1
if sudo -k -n true > /dev/null 2>&1; then
    ansible_extra_args=''
else
    ansible_extra_args='--ask-sudo-pass'
fi

echo ${this_dir}
ansible-playbook -i 'localhost,' -e "source_root=${this_dir}" \
    $ansible_extra_args ./setup.yml
