- hosts: localhost
  connection: local
  vars:
    adobe_font_list:
      - source-code-pro
      - source-sans-pro
      - source-serif-pro
  vars_prompt:
    - name: main_user_name
      prompt: "main user name for this machine"
      private: no
    - name: tmux_share_password
      prompt:  "guest password for sharing tmux sessions"
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7
  tasks:
    - name: Install apt update stamp hook
      copy: src=etc/apt/apt.conf.d/15update-stamp dest=/etc/apt/apt.conf.d/15udpate-stamp owner=root group=root
      become: yes

    - name: Upgrade all system packages
      apt: upgrade=yes update_cache=yes cache_valid_time=86400
      become: yes

    - name: Install applications
      apt: name={{item}} state=latest
      become: yes
      with_items:
        - git
        - emacs
        - neovim
        - tmux
        - zsh
        - tree
        - htop
        - mtr-tiny
        - speedcrunch
        - chromium-browser
        - clementine
        - gnome-tweak-tool
        - nautilus
        - git-gui
        - gitg
        - build-essential
        - apt-file
        - cloc
        - openssh-server
        - hexchat

    - name: set up git user info
      command: git config --global user.{{item.field}} {{item.value}}
      with_items:
        - {field: name, value: Paul Weaver}

    - name: set up git aliases
      command: git config --global alias.{{name}} "{{ name }}"
      with_items:
        - name: lg
          command: "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
        - name: currentbranch
          command: "rev-parse --abbrev-ref HEAD"
        - name: branchdiff
          command: "! f() { git diff $(git merge-base $(git currentbranch) ${1:-master}); }; f"
        # http://megakemp.com/2016/08/25/git-undo/
        - name: undo
          command: "!f() { git reset --hard $(git currentbranch)@{${1-1}}; }; f"
        # https://csswizardry.com/2017/05/little-things-i-like-to-do-with-git/
        # See which branches you recently worked on:
        - name: recent
          command: for-each-ref --count=10 --sort=-committerdate refs/heads/ --format="%(refname:short)"


    - name: setup main user
      user:
        name: "{{ main_user_name }}"
        shell: /usr/bin/zsh
        generate_ssh_key: yes
      become: yes

    - name: generate SSH key
      command: ssh-keygen -f ~/.ssh/id_rsa -P ''
      args:
        creates: ~/.ssh/id_rsa

    - name: home dirs
      file: path=~/{{item}} state=directory
      with_items:
        - src
        - tmp
        - .emacs.d
        - .fonts

    - name: clone sources
      git: clone=yes repo={{item.repo}} dest=~/src/{{item.dest}}
      with_items:
        - repo: https://github.com/ch3pjw/dotfiles.git
          dest: dotfiles
        - repo: https://github.com/ch3pjw/zsh_prompt.git
          dest: zsh_prompt

    - stat: path=~/.fonts/source-code-pro
      register: fonts_present

    - name: Fetch Adobe fonts
      get_url:
        url: https://github.com/adobe-fonts/{{item}}/archive/release.zip
        dest: /tmp/{{item}}-release.zip
      with_items: "{{ adobe_font_list }}"
      when: fonts_present.stat.exists == False

    - name: Extract Adobe fonts
      unarchive:
        copy: no
        src: /tmp/{{item}}-release.zip
        dest: /tmp
      with_items: "{{ adobe_font_list }}"
      when: fonts_present.stat.exists == False

    - name: Install Adobe fonts
      copy: src=/tmp/{{item}}-release/OTF/ dest=~/.fonts/{{item}}/
      with_items: "{{ adobe_font_list }}"
      when: fonts_present.stat.exists == False

    - name: update font cache
      command: fc-cache -f -v

    - name: clean any pre-existing dotfiles
      file: path={{item}} state=absent
      with_items:
          - ~/.bashrc
          - ~/.zshrc

    - name: dotfile ~ links
      file: path={{item.dest}} state=link src={{item.src}}
      with_items:
          - src: ~/src/dotfiles/home/bin
            dest: ~/bin
          - src: ~/src/dotfiles/home/dot_zshrc
            dest: ~/.zshrc
          - src: ~/src/zsh_prompt/zsh_prompt
            dest: ~/.zsh_prompt
          - src: ~/src/dotfiles/home/dot_emacs.d/init.el
            dest: ~/.emacs.d/init.el
          - src: ~/src/dotfiles/home/dot_tmux.conf
            dest: ~/.tmux.conf
          - src: ~/src/dotfiles/home/dot_noserc
            dest: ~/.noserc
          - src: ~/src/dotfiles/home/dot_ghc/ghci.conf
            dest: ~/.ghc/ghci.conf

    - name: global tmux_share login shell
      copy:
        dest: /bin/tmux_share_guest_shell
        src: bin/tmux_share_guest_shell
        mode: u=rx,g=rx,o=rx
      become: yes

    - name: guest user for tmux_share
      user:
        name: guest
        comment: A dynamically enabled user for tmux_share
        createhome: no
        password: tmux_share_password
        shell: /bin/tmux_share_guest_shell
      become: yes

    - name: disable guest account
      command: usermod --lock guest
      become: yes
